language: php
php:
- 7.1
- 7.2
sudo: required
notifications:
  email:
    on_success: never
    on_failure: change
branches:
  only:
  - dev
  - "/\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
env:
- WP_VERSION=latest
cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - node_modules
  - vendor
before_install:
- sudo apt-get -qq update
install:
- composer install
before_script:
- if [[ ${TRAVIS_PHP_VERSION:0:3} != "7.1" ]] && php -v | grep -q 'Xdebug'; then phpenv
  config-rm xdebug.ini; fi
- bash bin/install-wp-tests.sh poi_test root '' localhost $WP_VERSION
script:
- vendor/bin/phpunit --configuration=phpunit.xml
- vendor/bin/phpcs --standard=phpcs.ruleset.xml *.php inc/
before_deploy:
- export TRAVIS_PROJECT_SLUG="$(basename $TRAVIS_BUILD_DIR)"
- curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
- chmod +x wp-cli.phar
- sudo mv wp-cli.phar /usr/local/bin/wp
- wp package install wp-cli/dist-archive-command
- composer install --no-dev --optimize-autoloader
- cd ../
- wp dist-archive $TRAVIS_PROJECT_SLUG $TRAVIS_BUILD_DIR/$TRAVIS_PROJECT_SLUG-$TRAVIS_TAG.zip
- cd $TRAVIS_BUILD_DIR
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: Sftj1vfS5Zve3YmePXStPimRy3m49jyS2dG6kuWRt/hhBqaf+y8nxXR+1QZvBc1kHUl7+3pHhleaLGWcXku3FVcz9lhJsrBufwVbz3IrhkgpSne4VUpkcyDWhxeDkoaY2xa/IOUN4ez2sPAe45fY4m6GxrzImOkrEiK37WlPF2nHgeev58wIzTOIKR9arDQ15VpyHEWm3pUTDDRXURBM/ncgoSfxq0wstFsJQ3Dq8TMYdnKDupBljD/u8Xo2T5HAI/XeCjHkoVNIW0UkS5X8Wewrh2XtK4c2RKD9vgQ2mBZ87AF7h1JL5VtLLJG/koGd4K0nba3OxV1DbeCL+A/c60Lw04asCmJoxr46/YdCl6mQwBqY5e+GCGK+DMKS6qgOS1jfeBineV0n4uZgdpPNd6Rn6eTipiK+J9lLzLiDXSNKkBtyf5USqpt3YhP4pu3yxTmStVBZQTfo/buF4vgPGKH312FokGfWnLP+ILpMLkQFgloWsb/eOdhpdVm1T3g/Ueypx0iNeDU55WmubL98K/YUVRhhwB8M5blXWb7a/lM2Opo65ffXK/uzPwTRSqlu41G/AdVpN2TFqfCcVyQIC2gEoHi8wtsELw2/l51AWPOCT+c8uBAYcLmCqGbX/FgYXkAAu1QrY+5VvfLSilS2X4NQirbjGxLaQVZsqhVuh3o=
  file: pressbooks-openstax-import-$TRAVIS_TAG.zip
  on:
    tags: true
    repo: BCcampus/pressbooks-openstax-import
    branch: dev
